name: Getting Deleted Branch Details

on: 
  delete:
    branches: ["*"]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for the branch ${{ github.event.ref }}"
